services:
  - type: web
    name: trackdown-bot
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: BOT_TOKEN
        value: 7233219216:AAFMv7UmrS8_t1j1h5BMv3lkUPF7sPHE3ag
      - key: HOST_URL
        sync: false
      - key: NODE_ENV
        value: production
